//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.586
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chocolatey.Explorer {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chocolatey.Explorer.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die by {0} ähnelt.
        /// </summary>
        internal static string authored_by {
            get {
                return ResourceManager.GetString("authored_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not download package information from &apos;{0}&apos; ähnelt.
        /// </summary>
        internal static string could_not_download {
            get {
                return ResourceManager.GetString("could_not_download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not parse package information. ähnelt.
        /// </summary>
        internal static string could_not_parse {
            get {
                return ResourceManager.GetString("could_not_parse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Getting list of packages on server ähnelt.
        /// </summary>
        internal static string getting_available_packages {
            get {
                return ResourceManager.GetString("getting_available_packages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Getting list of installed packages ähnelt.
        /// </summary>
        internal static string getting_installed_packages {
            get {
                return ResourceManager.GetString("getting_installed_packages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Getting package information for package: {0} ähnelt.
        /// </summary>
        internal static string getting_package_information {
            get {
                return ResourceManager.GetString("getting_package_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Install ähnelt.
        /// </summary>
        internal static string install {
            get {
                return ResourceManager.GetString("install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Install selected package ähnelt.
        /// </summary>
        internal static string install_long {
            get {
                return ResourceManager.GetString("install_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Installing package {0}... ähnelt.
        /// </summary>
        internal static string installing {
            get {
                return ResourceManager.GetString("installing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not find the installed packages directory ({0}), please change the install directory in the settings. ähnelt.
        /// </summary>
        internal static string lib_dir_not_found {
            get {
                return ResourceManager.GetString("lib_dir_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die n.a. ähnelt.
        /// </summary>
        internal static string not_available {
            get {
                return ResourceManager.GetString("not_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Number of installed packages:  {0} ähnelt.
        /// </summary>
        internal static string num_installed_packages {
            get {
                return ResourceManager.GetString("num_installed_packages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Number of packages:  {0} ähnelt.
        /// </summary>
        internal static string num_packages {
            get {
                return ResourceManager.GetString("num_packages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0:0.#} KB ähnelt.
        /// </summary>
        internal static string package_size_mb {
            get {
                return ResourceManager.GetString("package_size_mb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you really want to uninstall &apos;{0}&apos;? ähnelt.
        /// </summary>
        internal static string really_uninstall_package_msg {
            get {
                return ResourceManager.GetString("really_uninstall_package_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Uninstall ähnelt.
        /// </summary>
        internal static string really_uninstall_package_title {
            get {
                return ResourceManager.GetString("really_uninstall_package_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &amp;Uninstall ähnelt.
        /// </summary>
        internal static string uninstall {
            get {
                return ResourceManager.GetString("uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Uninstalling package {0}... ähnelt.
        /// </summary>
        internal static string uninstalling {
            get {
                return ResourceManager.GetString("uninstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Uninstall selected package ähnelt.
        /// </summary>
        internal static string unsinstall_long {
            get {
                return ResourceManager.GetString("unsinstall_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Updating package {0}... ähnelt.
        /// </summary>
        internal static string updating_package {
            get {
                return ResourceManager.GetString("updating_package", resourceCulture);
            }
        }
    }
}
