//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChocolateyGui.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChocolateyGui.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument can&apos;t be null or empty..
        /// </summary>
        public static string Argument_cant_be_null_or_empty {
            get {
                return ResourceManager.GetString("Argument_cant_be_null_or_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Console Output.
        /// </summary>
        public static string ChocolateyDialog_ConsoleOutput {
            get {
                return ResourceManager.GetString("ChocolateyDialog_ConsoleOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By: .
        /// </summary>
        public static string Controls_PackageListByAuthor {
            get {
                return ResourceManager.GetString("Controls_PackageListByAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to downloads.
        /// </summary>
        public static string Controls_PackageListDownloads {
            get {
                return ResourceManager.GetString("Controls_PackageListDownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags:.
        /// </summary>
        public static string Controls_PackageListTags {
            get {
                return ResourceManager.GetString("Controls_PackageListTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Controls_PackagesContextMenuDetails {
            get {
                return ResourceManager.GetString("Controls_PackagesContextMenuDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string Controls_PackagesContextMenuInstall {
            get {
                return ResourceManager.GetString("Controls_PackagesContextMenuInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin.
        /// </summary>
        public static string Controls_PackagesContextMenuPin {
            get {
                return ResourceManager.GetString("Controls_PackagesContextMenuPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reinstall.
        /// </summary>
        public static string Controls_PackagesContextMenuReinstall {
            get {
                return ResourceManager.GetString("Controls_PackagesContextMenuReinstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        public static string Controls_PackagesContextMenuUninstall {
            get {
                return ResourceManager.GetString("Controls_PackagesContextMenuUninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpin.
        /// </summary>
        public static string Controls_PackagesContextMenuUnpin {
            get {
                return ResourceManager.GetString("Controls_PackagesContextMenuUnpin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Controls_PackagesContextMenuUpdate {
            get {
                return ResourceManager.GetString("Controls_PackagesContextMenuUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid version string..
        /// </summary>
        public static string InvalidVersionString {
            get {
                return ResourceManager.GetString("InvalidVersionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string LocalSourceView_ButtonExport {
            get {
                return ResourceManager.GetString("LocalSourceView_ButtonExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Packages.
        /// </summary>
        public static string LocalSourceView_ButtonRefreshPkgs {
            get {
                return ResourceManager.GetString("LocalSourceView_ButtonRefreshPkgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update All.
        /// </summary>
        public static string LocalSourceView_ButtonUpdateAll {
            get {
                return ResourceManager.GetString("LocalSourceView_ButtonUpdateAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Word Exactly.
        /// </summary>
        public static string LocalSourceView_CheckboxMatchExact {
            get {
                return ResourceManager.GetString("LocalSourceView_CheckboxMatchExact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Only Packages with Updates.
        /// </summary>
        public static string LocalSourceView_CheckboxPkgsWithUpdates {
            get {
                return ResourceManager.GetString("LocalSourceView_CheckboxPkgsWithUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authors.
        /// </summary>
        public static string LocalSourceView_Grid_Authors {
            get {
                return ResourceManager.GetString("LocalSourceView_Grid_Authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Version.
        /// </summary>
        public static string LocalSourceView_Grid_LatestVersion {
            get {
                return ResourceManager.GetString("LocalSourceView_Grid_LatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string LocalSourceView_Grid_Name {
            get {
                return ResourceManager.GetString("LocalSourceView_Grid_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string LocalSourceView_Grid_Version {
            get {
                return ResourceManager.GetString("LocalSourceView_Grid_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search:.
        /// </summary>
        public static string LocalSourceView_SearchBoxText {
            get {
                return ResourceManager.GetString("LocalSourceView_SearchBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authors:.
        /// </summary>
        public static string PackageView_Authors {
            get {
                return ResourceManager.GetString("PackageView_Authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string PackageView_ButtonInstall {
            get {
                return ResourceManager.GetString("PackageView_ButtonInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin.
        /// </summary>
        public static string PackageView_ButtonPin {
            get {
                return ResourceManager.GetString("PackageView_ButtonPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reinstall.
        /// </summary>
        public static string PackageView_ButtonReinstall {
            get {
                return ResourceManager.GetString("PackageView_ButtonReinstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        public static string PackageView_ButtonUninstall {
            get {
                return ResourceManager.GetString("PackageView_ButtonUninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpin.
        /// </summary>
        public static string PackageView_ButtonUnpin {
            get {
                return ResourceManager.GetString("PackageView_ButtonUnpin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string PackageView_ButtonUpdate {
            get {
                return ResourceManager.GetString("PackageView_ButtonUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependencies.
        /// </summary>
        public static string PackageView_Dependencies {
            get {
                return ResourceManager.GetString("PackageView_Dependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string PackageView_Description {
            get {
                return ResourceManager.GetString("PackageView_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads.
        /// </summary>
        public static string PackageView_Downloads {
            get {
                return ResourceManager.GetString("PackageView_Downloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        public static string PackageView_Gallery {
            get {
                return ResourceManager.GetString("PackageView_Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last update.
        /// </summary>
        public static string PackageView_LastUpdate {
            get {
                return ResourceManager.GetString("PackageView_LastUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        public static string PackageView_License {
            get {
                return ResourceManager.GetString("PackageView_License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  | Maintainers: .
        /// </summary>
        public static string PackageView_Maintainers {
            get {
                return ResourceManager.GetString("PackageView_Maintainers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package ID.
        /// </summary>
        public static string PackageView_PackageID {
            get {
                return ResourceManager.GetString("PackageView_PackageID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Size.
        /// </summary>
        public static string PackageView_PackageSize {
            get {
                return ResourceManager.GetString("PackageView_PackageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Site.
        /// </summary>
        public static string PackageView_ProjectSite {
            get {
                return ResourceManager.GetString("PackageView_ProjectSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Notes.
        /// </summary>
        public static string PackageView_ReleaseNotes {
            get {
                return ResourceManager.GetString("PackageView_ReleaseNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Abuse.
        /// </summary>
        public static string PackageView_ReportAbuse {
            get {
                return ResourceManager.GetString("PackageView_ReportAbuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string PackageView_Summary {
            get {
                return ResourceManager.GetString("PackageView_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Downloads.
        /// </summary>
        public static string PackageView_TotalDownloads {
            get {
                return ResourceManager.GetString("PackageView_TotalDownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authors:.
        /// </summary>
        public static string RemoteSourceView_Authors {
            get {
                return ResourceManager.GetString("RemoteSourceView_Authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Back a Page.
        /// </summary>
        public static string RemoteSourceView_ButtonGoBackAPage {
            get {
                return ResourceManager.GetString("RemoteSourceView_ButtonGoBackAPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string RemoteSourceView_ButtonGoForwardAPage {
            get {
                return ResourceManager.GetString("RemoteSourceView_ButtonGoForwardAPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to First Page.
        /// </summary>
        public static string RemoteSourceView_ButtonGotoFirstPage {
            get {
                return ResourceManager.GetString("RemoteSourceView_ButtonGotoFirstPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        public static string RemoteSourceView_ButtonGotoLastPage {
            get {
                return ResourceManager.GetString("RemoteSourceView_ButtonGotoLastPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Packages.
        /// </summary>
        public static string RemoteSourceView_ButtonRefreshPkgs {
            get {
                return ResourceManager.GetString("RemoteSourceView_ButtonRefreshPkgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Versions.
        /// </summary>
        public static string RemoteSourceView_CheckboxAllVersions {
            get {
                return ResourceManager.GetString("RemoteSourceView_CheckboxAllVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Prerelease.
        /// </summary>
        public static string RemoteSourceView_CheckboxIncludePrerelease {
            get {
                return ResourceManager.GetString("RemoteSourceView_CheckboxIncludePrerelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match Word Exactly.
        /// </summary>
        public static string RemoteSourceView_CheckboxMatchExactly {
            get {
                return ResourceManager.GetString("RemoteSourceView_CheckboxMatchExactly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to downloads.
        /// </summary>
        public static string RemoteSourceView_Downloads {
            get {
                return ResourceManager.GetString("RemoteSourceView_Downloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search:.
        /// </summary>
        public static string RemoteSourceView_SearchBoxText {
            get {
                return ResourceManager.GetString("RemoteSourceView_SearchBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This PC.
        /// </summary>
        public static string Resources_ThisPC {
            get {
                return ResourceManager.GetString("Resources_ThisPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string SettingsView_About {
            get {
                return ResourceManager.GetString("SettingsView_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string SettingsView_ButtonCancel {
            get {
                return ResourceManager.GetString("SettingsView_ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string SettingsView_ButtonNew {
            get {
                return ResourceManager.GetString("SettingsView_ButtonNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string SettingsView_ButtonRemove {
            get {
                return ResourceManager.GetString("SettingsView_ButtonRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SettingsView_ButtonSave {
            get {
                return ResourceManager.GetString("SettingsView_ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chocolatey Gui.
        /// </summary>
        public static string SettingsView_ChocoGui {
            get {
                return ResourceManager.GetString("SettingsView_ChocoGui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        public static string SettingsView_Credits {
            get {
                return ResourceManager.GetString("SettingsView_Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features.
        /// </summary>
        public static string SettingsView_Features {
            get {
                return ResourceManager.GetString("SettingsView_Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string SettingsView_Options {
            get {
                return ResourceManager.GetString("SettingsView_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string SettingsView_PropertyDescription {
            get {
                return ResourceManager.GetString("SettingsView_PropertyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string SettingsView_PropertyName {
            get {
                return ResourceManager.GetString("SettingsView_PropertyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string SettingsView_PropertyValue {
            get {
                return ResourceManager.GetString("SettingsView_PropertyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Notes.
        /// </summary>
        public static string SettingsView_ReleaseNotes {
            get {
                return ResourceManager.GetString("SettingsView_ReleaseNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsView_Settings {
            get {
                return ResourceManager.GetString("SettingsView_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sources.
        /// </summary>
        public static string SettingsView_Sources {
            get {
                return ResourceManager.GetString("SettingsView_Sources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate.
        /// </summary>
        public static string SettingsView_SourcesCertificate {
            get {
                return ResourceManager.GetString("SettingsView_SourcesCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate Pass.
        /// </summary>
        public static string SettingsView_SourcesCertificatePass {
            get {
                return ResourceManager.GetString("SettingsView_SourcesCertificatePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string SettingsView_SourcesDisabled {
            get {
                return ResourceManager.GetString("SettingsView_SourcesDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string SettingsView_SourcesId {
            get {
                return ResourceManager.GetString("SettingsView_SourcesId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Disabled.
        /// </summary>
        public static string SettingsView_SourcesIsDisabled {
            get {
                return ResourceManager.GetString("SettingsView_SourcesIsDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string SettingsView_SourcesPassword {
            get {
                return ResourceManager.GetString("SettingsView_SourcesPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string SettingsView_SourcesPath {
            get {
                return ResourceManager.GetString("SettingsView_SourcesPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string SettingsView_SourcesPriority {
            get {
                return ResourceManager.GetString("SettingsView_SourcesPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string SettingsView_SourcesSource {
            get {
                return ResourceManager.GetString("SettingsView_SourcesSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string SettingsView_SourcesUsername {
            get {
                return ResourceManager.GetString("SettingsView_SourcesUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chocolatey.
        /// </summary>
        public static string SettingsView_SubheaderChoco {
            get {
                return ResourceManager.GetString("SettingsView_SubheaderChoco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elevate By Default.
        /// </summary>
        public static string SettingsView_ToggleElevateByDefault {
            get {
                return ResourceManager.GetString("SettingsView_ToggleElevateByDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Console Output.
        /// </summary>
        public static string SettingsView_ToggleShowConsoleOutput {
            get {
                return ResourceManager.GetString("SettingsView_ToggleShowConsoleOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string ShellView_ButtonAbout {
            get {
                return ResourceManager.GetString("ShellView_ButtonAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string ShellView_ButtonSettings {
            get {
                return ResourceManager.GetString("ShellView_ButtonSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chocolatey.
        /// </summary>
        public static string SourcesView_Choco {
            get {
                return ResourceManager.GetString("SourcesView_Choco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LineType must be a semantic version..
        /// </summary>
        public static string TypeMustBeASemanticVersion {
            get {
                return ResourceManager.GetString("TypeMustBeASemanticVersion", resourceCulture);
            }
        }
    }
}
